apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  labels:
    argocd.argoproj.io/instance: guestbook
  name: guestbook-ui
  namespace: argocd
spec:
  host: guestbook-ui-argocd.apps.ocp.corp.myservices.digital
  to:
    kind: Service
    name: guestbook-ui
    weight: 100
  wildcardPolicy: None
