apiVersion: v1
data:
  test.txt: test123
kind: ConfigMap
metadata:
  creationTimestamp: '2021-05-06T06:36:24Z'
  name: test2-cm
  namespace: argocd
  resourceVersion: '42435090'
  selfLink: /api/v1/namespaces/argocd/configmaps/test2-cm
  uid: 60a07b69-ae35-11eb-a602-fefe3e6f83d8
